# Generated by Django 3.2.4 on 2021-07-18 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieTheaters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movieName', models.CharField(max_length=200)),
                ('theaterList', models.TextField()),
                ('movieImage', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='TheaterDetails',
            fields=[
                ('theaterName', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('screen_1', models.CharField(max_length=100)),
                ('screen_2', models.CharField(max_length=100)),
                ('screen_3', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SeatBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('screen', models.CharField(max_length=100)),
                ('Seats', models.CharField(max_length=100)),
                ('Movie', models.CharField(max_length=100)),
                ('theaterName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Movies.theaterdetails')),
                ('userEmail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.adduser')),
            ],
        ),
    ]
