# Generated by Django 3.2.4 on 2021-07-18 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='seatbooking',
            name='userName',
            field=models.CharField(default='a', max_length=50),
        ),
    ]
