# Generated by Django 3.2.4 on 2021-07-18 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Movies', '0002_seatbooking_username'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MovieTheaters',
            new_name='MovieDetails',
        ),
    ]
